version: '3'
services:
  db:
    image: microsoft/mssql-server-linux
    container_name: bearhead
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # REMARK: This is currently required, needs investigation
    volumes:
      - sqlinux-volume:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bearnose
    environment:
      - "ConnectionStrings:MicroSB=Server=db,1433;Database=microsb;User Id=sa;Password=Password1;MultipleActiveResultSets=True"
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    volumes:
      - './:/home/'

networks:
  default:
    external:
      name: nat

volumes:
  sqlinux-volume:
